### PR TITLE
Ci md css js

### PR DESCRIPTION
**Pull request by vchase209**
#79

### CODE REVIEW

**Review by neelay-j — CHANGES_REQUESTED** [review]
`main.yml` looks like it does what we want it to (i.e. lint all filetypes and then store logs). However, the meeting minutes should be reformatted. The filenames should have the following format, as specified by the cse 110 instructors: `mmddyy-meetingtopic.md` (e.g. `CI-CD-MeetingMinutes11-12.md` should be renamed to `111222-ci-cd.md`). Also format the notes as bullet points, because as of right now all the notes in the `Discussion` section are compressed into a paragraph instead of having newlines between them.

**Review by yashpuneet — APPROVED** [review]
Great job implementing all linting and file validation tests in an effective way. The Initial CI works great and has provided enough information for us to fix consistency issues across our files at this stage. Also, great job with the documentation of the CI design process!

**Comment by vchase209** [comment]
Changed md formatting

**Review by yashpuneet — APPROVED** [review]
Thanks for changing the file names and fixing the formatting issues.

**Pull request merged**
